name: "morning-insight"
description: "ğ’¢ğ‘’ğ“‰'ğ“ˆ ğ’¶ ğ“†ğ“Šğ‘œğ“‰ğ‘’."
author: pmfs1
inputs:
  GSM-7_COMPATIBLE:
    description: "IF TRUE THE RESULT WILL BE GSM-7 (SMS) COMPATIBLE, MEANING, IT WILL BE LIMITED TO 160 CHARACTERS; OTHERWISE IT WON'T."
    required: false
    default: false
outputs:
  OUTPUT:
    description: "OUTPUT"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GSM-7_COMPATIBLE }}