# GET(): SELECTS A RANDOM OBJECT FROM THE JSONC DATABASE (IF IT'S RUNNING IN DOCKER CONTAINER OR GITHUB ACTIONS USES THE LOCAL FILE OTHERWISE USES THE REMOTE FILE). PARSES IT. FORMATS IT IN A 'QUOTE (AUTHOR)' STYLE (IF THE AUTHOR IS NULL IT DOESN'T GET PRINTED). IF THE GSM-7_COMPATIBLE FLAG IS TRUE, SEARCHES FOR A QUOTE UNTIL IT FINDS ONE THAT IS SMALLER THAN 160 CHARACTERS. THEN PRINTS IT.
function GET(# IF TRUE THE RESULT WILL BE GSM-7 (SMS) COMPATIBLE, MEANING, IT WILL BE LIMITED TO 160 CHARACTERS; OTHERWISE IT WON'T.
[Parameter(Mandatory = $false)]
[bool]$GSM_7_COMPATIBLE = $false) {
    $QUOTE = $null
    # IF THE JSONC DATABASE IS RUNNING IN DOCKER CONTAINER OR GITHUB ACTIONS USES THE LOCAL FILE OTHERWISE USES THE REMOTE FILE.
    $PATH = switch ($env:GITHUB_ACTIONS) {
        $true { '/DATABASE.jsonc' }
        Default { './DATABASE.jsonc' }
    }
    while ($null -eq $QUOTE) {
        $QUOTE = Get-Content -Path $PATH | ConvertFrom-Json | Get-Random | ForEach-Object {
            # PARSES IT AND FORMATS IT IN A 'QUOTE (AUTHOR)' STYLE (IF THE AUTHOR IS NULL IT DOESN'T GET PRINTED).
            if ($_.AUTHOR) {
                "$($_.QUOTE) ($($_.AUTHOR))"
            }
            else {
                "$($_.QUOTE)"
            }
        }
        # IF THE GSM-7_COMPATIBLE FLAG IS TRUE, SETS THE QUOTE TO $null IF IT'S BIGGER THAN 160 CHARACTERS; IN ORDER TO KEEP SEARCHING FOR A QUOTE UNTIL IT FINDS ONE THAT IS SMALLER THAN 160 CHARACTERS. OTHERWISE IT TRANSFORMS THE QUOTE INTO GSM-7 (SMS) COMPATIBLE FORMAT (REMOVING ALL UNICODE AND UNSUPPORTED CHARACTERS, EXCEPT PARENTHESES, COMMAS, AND PERIODS).
        if ($GSM_7_COMPATIBLE) {
            if ($QUOTE.Length -gt 160) {
                $QUOTE = $null
            }
        }
        else {
            $QUOTE = $QUOTE -replace '[^\p{L}\p{N}\p{P}\p{Z}]', ''
        }
    }
    # PRINTS THE QUOTE.
    Write-Output $QUOTE
    # SETS THE QUOTE AS THE OUTPUT OF THE ACTION, IF RUN IN GITHUB ACTIONS.
    if ($env:GITHUB_ACTIONS) {
        Write-Output "OUTPUT=$QUOTE" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
    }
}

$GSM_7_COMPATIBLE = switch ($args[0]) {
    'true' { $true }
    Default { $false }
}
# CALLS THE GET() FUNCTION WITH THE GSM_7_COMPATIBLE FLAG SET TO FALSE BY DEFAULT; OTHERWISE IT USES THE VALUE PASSED AS THE FIRST ARGUMENT.
GET($GSM_7_COMPATIBLE)