name: 'DISCORD QUOTE SENDER'
on:
  workflow_dispatch:
  schedule:
   - cron: '0 23 * * *'
jobs:
  DISCORD_QUOTE_SENDER:
    name: 'DISCORD QUOTE SENDER'
    runs-on: ubuntu-22.04
    steps:
      - id: 'GET'
        name: 'GET'
        uses: pmfs1/morning-insight@1.0.0
      - name: 'SEND'
        uses: MineBartekSA/discord-webhook@v2.1
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          content: "> *${{ steps.GET.outputs.OUTPUT }}*"