name: 'DISCORD QUOTE SENDER'
on:
  workflow_dispatch:
  schedule:
   - cron: '0 7 * * *'
jobs:
  GET:
    name: 'GET'
    runs-on: ubuntu-22.04
    outputs:
      OUTPUT: ${{ steps.GET.outputs.OUTPUT }}
    steps:
      - id: 'GET'
        uses: pmfs1/morning-insight@3.0.0
  SEND:
    name: 'SEND'
    runs-on: ubuntu-22.04
    needs: GET
    steps:
      - name: 'SEND'
        uses: MineBartekSA/discord-webhook@v2.1
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          content: "> *${{ needs.GET.outputs.OUTPUT }}*"